# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_DATABASE: circle_test
          DB_USERNAME: root
          DB_PASSWORD: ubuntu
          SESSION_DRIVER: database
          CACHE_DRIVER: file
      - image: circleci/mysql:8.0
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_ROOT_PASSWORD=ubuntu
        - MYSQL_USER=ubuntu
        - MYSQL_PASSWORD=ubuntu
        - MYSQL_DATABASE=circle_test

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip bcmath
      - run: sudo apt-get install mysql-client

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install Dependencies

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-

      # prepare the database
      - run: mysqladmin create furahasms_testing --user="root" --password="root"
      - run: php artisan migrate --env=testing --force

      # run tests
      - run: ./vendor/bin/phpuni
