<?php


namespace Okotieno\AcademicYear\Tests\Unit;


use Okotieno\AcademicYear\Models\AcademicYear;
use Okotieno\AcademicYear\Models\Holiday;
use Okotieno\PermissionsAndRoles\Models\Permission;
use Tests\TestCase;

class AcademicYearHolidayTest extends TestCase
{
  public function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-holiday
   */

  public function should_create_academic_years_holiday()
  {
    Permission::factory()->state(['name' => 'create academic year'])->create();
    Holiday::factory()->count(10)->create();
    $academicYear = AcademicYear::factory()->make()->toArray();
    $this->user->givePermissionTo('create academic year');
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years', $academicYear);
    $this->assertNotEmpty(
      AcademicYear::where('name', $academicYear['name'])->first()->holidays->toArray());
  }

}
