<?php


namespace Okotieno\AcademicYear\Tests\Unit;


use Okotieno\AcademicYear\Models\AcademicYear;
use Okotieno\AcademicYear\Models\ArchivableItem;
use Okotieno\PermissionsAndRoles\Models\Permission;
use Tests\TestCase;

class AcademicYearArchivesTest extends TestCase
{
  public function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function unauthenticated_user_cannot_close_academic_year_admissions()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->postJson('/api/academic-years/' . $academicYear->id . '/close/admissions')
      ->assertStatus(401);
  }


  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthorised_user_cannot_close_academic_year_admissions()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/admissions')
      ->assertStatus(403);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function authorised_user_can_close_academic_year_admissions()
  {
    Permission::factory()->state(['name' => 'close academic year admissions'])->create();

    $academicYear = AcademicYear::factory()->create();
    $this->user->givePermissionTo('close academic year admissions');

    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/admissions')
      ->assertStatus(200)
      ->assertJsonStructure(['saved', 'message']);

    $archivableItem = AcademicYear::find($academicYear->id)
      ->archivableItems()
      ->wherePivot('archivable_item_id', ArchivableItem::admissions()->first()->id)
      ->get()
      ->toArray();
    $this->assertNotEmpty($archivableItem);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function unauthenticated_user_cannot_close_academic_year_financial_plan()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->postJson('/api/academic-years/' . $academicYear->id . '/close/financial-plan')
      ->assertStatus(401);
  }


  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthorised_user_cannot_close_academic_year_financial_plan()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/financial-plan')
      ->assertStatus(403);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function authorised_user_can_close_academic_year_financial_plan()
  {
    Permission::factory()->state(['name' => 'close academic year financial plan'])->create();

    $academicYear = AcademicYear::factory()->create();
    $this->user->givePermissionTo('close academic year financial plan');
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/financial-plan')
      ->assertStatus(200)
      ->assertJsonStructure(['saved', 'message']);

    $archivableItem = AcademicYear::find($academicYear->id)
      ->archivableItems()
      ->wherePivot('archivable_item_id', ArchivableItem::financialPlans()->first()->id)
      ->get()
      ->toArray();
    $this->assertNotEmpty($archivableItem);
  }
  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthenticated_user_cannot_close_academic_year_subject_creation()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->postJson('/api/academic-years/' . $academicYear->id . '/close/subject-creation')
      ->assertStatus(401);
  }


  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthorised_user_cannot_close_academic_year_subject_creation()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/subject-creation')
      ->assertStatus(403);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function authorised_user_can_close_academic_year_subject_creation()
  {
    Permission::factory()->state(['name' => 'close academic year subject creation'])->create();

    $academicYear = AcademicYear::factory()->create();
    $this->user->givePermissionTo('close academic year subject creation');
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/subject-creation')
      ->assertStatus(200)
      ->assertJsonStructure(['saved', 'message']);

    $archivableItem = AcademicYear::find($academicYear->id)
      ->archivableItems()
      ->wherePivot('archivable_item_id', ArchivableItem::subjectCreations()->first()->id)
      ->get()
      ->toArray();
    $this->assertNotEmpty($archivableItem);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthenticated_user_cannot_close_academic_year_score_amendment()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->postJson('/api/academic-years/' . $academicYear->id . '/close/score-amendment')
      ->assertStatus(401);
  }


  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthorised_user_cannot_close_academic_year_score_amendment()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/score-amendment')
      ->assertStatus(403);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function authorised_user_can_close_academic_year_score_amendment()
  {
    Permission::factory()->state(['name' => 'close academic year score amendment'])->create();

    $academicYear = AcademicYear::factory()->create();
    $this->user->givePermissionTo('close academic year score amendment');
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/score-amendment')
      ->assertStatus(200)
      ->assertJsonStructure(['saved', 'message']);

    $archivableItem = AcademicYear::find($academicYear->id)
      ->archivableItems()
      ->wherePivot('archivable_item_id', ArchivableItem::scoreAmendments()->first()->id)
      ->get()
      ->toArray();
    $this->assertNotEmpty($archivableItem);
  }
  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthenticated_user_cannot_close_academic_year_timetable_amendment()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->postJson('/api/academic-years/' . $academicYear->id . '/close/timetable-amendment')
      ->assertStatus(401);
  }


  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */


  public function unauthorised_user_cannot_close_academic_year_timetable_amendment()
  {
    $academicYear = AcademicYear::factory()->create();
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/timetable-amendment')
      ->assertStatus(403);
  }

  /**
   * POST /academic-years
   *
   * @test
   * @group post-request
   * @group academic-year-archives
   */

  public function authorised_user_can_close_academic_year_timetable_amendment()
  {
    Permission::factory()->state(['name' => 'close academic year timetable amendment'])->create();

    $academicYear = AcademicYear::factory()->create();
    $this->user->givePermissionTo('close academic year timetable amendment');
    $this->actingAs($this->user, 'api')
      ->postJson('/api/academic-years/' . $academicYear->id . '/close/timetable-amendment')
      ->assertStatus(200)
      ->assertJsonStructure(['saved', 'message']);

    $archivableItem = AcademicYear::find($academicYear->id)
      ->archivableItems()
      ->wherePivot('archivable_item_id', ArchivableItem::timetableAmendments()->first()->id)
      ->get()
      ->toArray();
    $this->assertNotEmpty($archivableItem);
  }
}
