name: Laravel

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Create database
        run: |
          mkdir -p database
          touch database/database.sqlite
          sudo apt-get install php-sqlite3
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      - name: Install Dependencies
        run: |
          composer self-update
          composer install --prefer-source --no-interaction --dev
          composer require --dev php-coveralls/php-coveralls
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        run: vendor/bin/phpunit
